name: Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: rpnlib

    - uses: actions/checkout@v2
      with:
        repository: ThrowTheSwitch/Unity
        path: unity

    - uses: actions/github-script@v4
      id: esp8266-release
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const releaseObj = await github.repos.getLatestRelease({
            owner: "esp8266",
            repo: "Arduino"
          });

          for (const asset of releaseObj.data.assets) {
            if (asset.name.startsWith("esp8266") && asset.name.endsWith(".zip")) {
              core.setOutput("tag", releaseObj.data.tag_name);
              core.setOutput("url", asset.browser_download_url);
              return;
            }
          }

          throw new Error("Could not fetch esp8266 release");

    - run: |
        curl -o esp8266.zip -L ${{ steps.esp8266-release.outputs.url }}
        unzip esp8266.zip
        rm esp8266.zip

    - name: Run tests
      run: |
        sudo apt install cmake
        cmake \
          -DESP8266_ARDUINO_CORE_PATH=${GITHUB_WORKSPACE}/esp8266-${{ steps.esp8266-release.outputs.tag }} \
          -DUNITY_PATH=${GITHUB_WORKSPACE}/unity/src \
          -S rpnlib/examples/host \
          -B build
        cmake --build build --target piotest
        ./build/piotest
